version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20.11.1
    commands:
      - echo Installing dependencies...
      - npm install -g @angular/cli@17.3.8
      - npm install
  build:
    commands:
      - echo Building the Angular application...
      - ng build --configuration production
  post_build:
    commands:
       - echo Checking build output directory...
      - ls -al dist/
      - ls -al dist/kookur-FE/
      - echo Syncing build output to S3...
      - aws s3 sync dist/kookur-FE/ s3://kookur-frontend --delete
      - if [ $? -ne 0 ]; then echo "S3 sync failed"; exit 1; fi 
