version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20.11.1
    commands:
      - echo Installing dependencies...
      - npm install -g @angular/cli@17.3.8
      - npm install
  build:
    commands:
      - echo Building the Angular application...
      - ng build --configuration production
  post_build:
    commands:
      - echo Build completed successfully.
      - aws s3 sync dist/kookur-fe/browser/ s3://kookur-frontend --delete
      - echo Creating CloudFront invalidation
      - aws cloudfront create-invalidation --distribution-id EFD6D8GULOR4B --paths "/*"  
